from big_ol_pile_of_manim_imports import *

class QuadraticProof(Scene):
    def construct(self):
        formula_tex = TexMobject("a{x}^{2}+bx+c=0")
        formula_tex.scale(1.5)
        take_away_c = TexMobject("a{x}^{2}+bx=-c")
        take_away_c.scale(1.5)
        divide_a = TexMobject("{x}^{2}+\\frac{b}{a}x=-\\frac{c}{a}")
        divide_a.scale(1.5)
        add_b_divide_twoa_squared = TexMobject("{x}^{2}+\\frac{b}{a}x+\\left(\\frac{b}{2a}\\right)^{2}=-\\frac{c}{a}+\left(\\frac{b}{2a}\\right)^{2}")
        add_b_divide_twoa_squared.scale(1.5)
        combine_lhs = TexMobject("\\left(x+\\frac{b}{2a}\\right)^{2}=-\\frac{c}{a}+\\frac{{b}^{2}}{4{a}^{2}}")
        combine_lhs.scale(1.5)
        flip_rhs = TexMobject("\\left(x+\\frac{b}{2a}\\right)^{2}=\\frac{{b}^{2}}{4{a}^{2}}-\\frac{c}{a}")
        flip_rhs.scale(1.5)
        multiply_foura = TexMobject("\\left(x+\\frac{b}{2a}\\right)^{2}=\\frac{{b}^{2}}{4{a}^{2}}-\\frac{4ac}{4{a}^{2}}")
        multiply_foura.scale(1.5)
        subtract_rhs = TexMobject("\\left(x+\\frac{b}{2a}\\right)^{2}=\\frac{{b}^{2}-4ac}{4{a}^{2}}")
        subtract_rhs.scale(1.5)
        square_root = TexMobject("\\sqrt{\\left(x+\\frac{b}{2a}\\right)^{2}}=\\pm\\sqrt{\\frac{{b}^{2}-4ac}{4{a}^{2}}}")
        square_root.scale(1.5)
        after_root = TexMobject("x+\\frac{b}{2a}=\\pm\\sqrt{\\frac{{b}^{2}-4ac}{4{a}^{2}}}")
        after_root.scale(1.5)
        single_x = TexMobject("x=-\\frac{b}{2a}\\pm\\sqrt{\\frac{{b}^{2}-4ac}{4{a}^{2}}}")
        single_x.scale(1.5)
        sqrt_fourasquared = TexMobject("x=-\\frac{b}{2a}\\pm\\frac{\\sqrt{{b}^{2}-4ac}}{2a}")
        sqrt_fourasquared.scale(1.5)
        final_answer = TexMobject("x=\\frac{-b\\pm\\sqrt{{b}^{2}-4ac}}{2a}")
        final_answer.scale(1.5)
        self.play(Write(formula_tex))
        self.wait(3)
        self.play(ReplacementTransform(formula_tex, take_away_c))
        self.wait(2)
        self.play(ReplacementTransform(take_away_c, divide_a))
        self.wait(2)
        self.play(ReplacementTransform(divide_a, add_b_divide_twoa_squared))
        self.wait(3)
        self.play(ReplacementTransform(add_b_divide_twoa_squared, combine_lhs))
        self.wait()
        self.play(ReplacementTransform(combine_lhs, flip_rhs))
        self.wait()
        self.play(ReplacementTransform(flip_rhs, multiply_foura))
        self.wait()
        self.play(ReplacementTransform(multiply_foura, subtract_rhs))
        self.wait(2)
        self.play(ReplacementTransform(subtract_rhs, square_root))
        self.wait(1.5)
        self.play(ReplacementTransform(square_root, after_root))
        self.wait(2)
        self.play(ReplacementTransform(after_root, single_x))
        self.wait()
        self.play(ReplacementTransform(single_x, sqrt_fourasquared))
        self.wait(1.5)
        self.play(ReplacementTransform(sqrt_fourasquared, final_answer))
        self.wait(10)